// Choice Properties — Replit Static File Server
// Serves the static site and generates config.js from environment variables

const express = require('express');
const path    = require('path');
const fs      = require('fs');
const crypto  = require('crypto');

const app  = express();
const PORT = process.env.PORT || 5000;
const ROOT = __dirname;

// ── Security headers ──────────────────────────────────────────────────────────
app.use((req, res, next) => {
  res.setHeader('X-Frame-Options', 'DENY');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin');
  res.setHeader('Permissions-Policy', 'camera=(), microphone=(), geolocation=()');
  next();
});

// ── Generate config.js from environment variables ─────────────────────────────
function buildConfig() {
  const supabaseUrl    = process.env.SUPABASE_URL      || '';
  const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';
  const siteUrl        = (process.env.SITE_URL || '').replace(/\/$/, '');

  const missing = [];
  if (!supabaseUrl)     missing.push('SUPABASE_URL');
  if (!supabaseAnonKey) missing.push('SUPABASE_ANON_KEY');

  if (missing.length) {
    console.warn('⚠  Missing environment variables:', missing.join(', '));
    console.warn('   The site will load but Supabase features will not work.');
    console.warn('   Add secrets via the Replit Secrets panel (lock icon).');
  }

  const config = {
    SUPABASE_URL:      supabaseUrl,
    SUPABASE_ANON_KEY: supabaseAnonKey,
    IMAGEKIT_URL:        process.env.IMAGEKIT_URL        || '',
    IMAGEKIT_PUBLIC_KEY: process.env.IMAGEKIT_PUBLIC_KEY || '',
    GEOAPIFY_API_KEY:    process.env.GEOAPIFY_API_KEY    || '',
    COMPANY_NAME:     process.env.COMPANY_NAME     || 'Choice Properties',
    COMPANY_EMAIL:    process.env.COMPANY_EMAIL    || 'hello@choiceproperties.com',
    COMPANY_PHONE:    process.env.COMPANY_PHONE    || '',
    COMPANY_TAGLINE:  process.env.COMPANY_TAGLINE  || 'Your trust is our standard.',
    COMPANY_ADDRESS:  process.env.COMPANY_ADDRESS  || '',
    LEASE_DEFAULT_LATE_FEE_FLAT:  Number(process.env.LEASE_DEFAULT_LATE_FEE_FLAT)  || 50,
    LEASE_DEFAULT_LATE_FEE_DAILY: Number(process.env.LEASE_DEFAULT_LATE_FEE_DAILY) || 10,
    LEASE_DEFAULT_EXPIRY_DAYS:    Number(process.env.LEASE_DEFAULT_EXPIRY_DAYS)    || 7,
    FEATURES: {
      CO_APPLICANT:    process.env.FEATURE_CO_APPLICANT    !== 'false',
      VEHICLE_INFO:    process.env.FEATURE_VEHICLE_INFO    !== 'false',
      DOCUMENT_UPLOAD: process.env.FEATURE_DOCUMENT_UPLOAD !== 'false',
      MESSAGING:       process.env.FEATURE_MESSAGING       !== 'false',
      REALTIME_UPDATES:process.env.FEATURE_REALTIME_UPDATES !== 'false',
    },
  };

  return `// Auto-generated by server.js on every startup — DO NOT EDIT
// Edit environment variables in the Replit Secrets panel instead
const CONFIG = {
  SUPABASE_URL:      '${config.SUPABASE_URL}',
  SUPABASE_ANON_KEY: '${config.SUPABASE_ANON_KEY}',
  IMAGEKIT_URL:        '${config.IMAGEKIT_URL}',
  IMAGEKIT_PUBLIC_KEY: '${config.IMAGEKIT_PUBLIC_KEY}',
  GEOAPIFY_API_KEY: '${config.GEOAPIFY_API_KEY}',
  COMPANY_NAME:     '${config.COMPANY_NAME}',
  COMPANY_EMAIL:    '${config.COMPANY_EMAIL}',
  COMPANY_PHONE:    '${config.COMPANY_PHONE}',
  COMPANY_TAGLINE:  '${config.COMPANY_TAGLINE}',
  COMPANY_ADDRESS:  '${config.COMPANY_ADDRESS}',
  LEASE_DEFAULT_LATE_FEE_FLAT:  ${config.LEASE_DEFAULT_LATE_FEE_FLAT},
  LEASE_DEFAULT_LATE_FEE_DAILY: ${config.LEASE_DEFAULT_LATE_FEE_DAILY},
  LEASE_DEFAULT_EXPIRY_DAYS:    ${config.LEASE_DEFAULT_EXPIRY_DAYS},
  FEATURES: {
    CO_APPLICANT:     ${config.FEATURES.CO_APPLICANT},
    VEHICLE_INFO:     ${config.FEATURES.VEHICLE_INFO},
    DOCUMENT_UPLOAD:  ${config.FEATURES.DOCUMENT_UPLOAD},
    MESSAGING:        ${config.FEATURES.MESSAGING},
    REALTIME_UPDATES: ${config.FEATURES.REALTIME_UPDATES},
  },
};

CONFIG.isLocalhost = ['localhost', '127.0.0.1'].includes(location.hostname);
CONFIG.baseUrl     = location.origin;

CONFIG.img = function(url, preset) {
  const fallback = url || '/assets/placeholder-property.jpg';
  if (!url) return '/assets/placeholder-property.jpg';
  if (!CONFIG.IMAGEKIT_URL || CONFIG.IMAGEKIT_URL.includes('YOUR_IMAGEKIT_ID')) return fallback;
  const transforms = {
    card:       'tr:w-600,q-80,f-webp',
    card_2x:    'tr:w-1200,q-80,f-webp',
    gallery:    'tr:w-1200,q-90,f-webp',
    gallery_2x: 'tr:w-2400,q-85,f-webp',
    strip:      'tr:w-80,h-60,c-maintain_ratio,q-70,f-webp',
    thumb:      'tr:w-120,h-120,c-maintain_ratio,q-75,f-webp',
    lightbox:   'tr:q-95,f-webp',
    og:         'tr:w-1200,h-630,c-force,fo-center,q-85,f-webp',
    avatar:     'tr:w-80,h-80,c-force,fo-face,q-80,f-webp',
    avatar_lg:  'tr:w-160,h-160,c-force,fo-face,q-85,f-webp',
  };
  const tr = transforms[preset] || transforms.gallery;
  if (url.startsWith(CONFIG.IMAGEKIT_URL)) {
    const clean = url.replace(/\\/tr:[^/]+/, '');
    return clean.replace(CONFIG.IMAGEKIT_URL, CONFIG.IMAGEKIT_URL + '/' + tr);
  }
  return url;
};

CONFIG.srcset = function(url, preset1x, preset2x) {
  const u1 = CONFIG.img(url, preset1x);
  const u2 = CONFIG.img(url, preset2x);
  if (!u1) return '';
  if (!u2 || u2 === u1) return u1;
  return u1 + ' 1x, ' + u2 + ' 2x';
};

Object.freeze(CONFIG);
Object.freeze(CONFIG.FEATURES);
`;
}

// Write config.js on startup
const configContent = buildConfig();
fs.writeFileSync(path.join(ROOT, 'config.js'), configContent);
console.log('✅ config.js generated from environment variables');

// ── Serve config.js with no-cache ────────────────────────────────────────────
app.get('/config.js', (req, res) => {
  res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
  res.setHeader('Content-Type', 'application/javascript');
  res.sendFile(path.join(ROOT, 'config.js'));
});

// ── Long-cache headers for static assets ─────────────────────────────────────
const LONG_CACHE = 'public, max-age=31536000, immutable';
app.use('/css',    express.static(path.join(ROOT, 'css'),    { maxAge: '1y' }));
app.use('/js',     express.static(path.join(ROOT, 'js'),     { maxAge: '1y' }));
app.use('/assets', express.static(path.join(ROOT, 'assets'), { maxAge: '1y' }));

// ── Serve all other static files ──────────────────────────────────────────────
app.use(express.static(ROOT, {
  extensions: ['html'],
  index: 'index.html',
}));

// ── Health check ──────────────────────────────────────────────────────────────
app.get('/health', (req, res) => res.json({ status: 'ok' }));

// ── 404 fallback ──────────────────────────────────────────────────────────────
app.use((req, res) => {
  const f404 = path.join(ROOT, '404.html');
  if (fs.existsSync(f404)) {
    res.status(404).sendFile(f404);
  } else {
    res.status(404).send('Not found');
  }
});

app.listen(PORT, '0.0.0.0', () => {
  console.log(`✅ Choice Properties running on http://0.0.0.0:${PORT}`);
  if (!process.env.SUPABASE_URL) {
    console.log('⚠  Add SUPABASE_URL and SUPABASE_ANON_KEY in the Secrets panel to enable all features.');
  }
});
